### PR TITLE
added nipype multi-core hpc talk

### PR DESCRIPTION
**Pull request by ccraddock**
I added a talk on multi-core

### CODE REVIEW

**Comment by satra** [comment]
@ccraddock - thanks i'm going to merge it and then work on it a bit tonight. but this looks good. i'm still waiting on access to an hpc cluster for folks to play with. if not we will spin up something on aws.

**Comment by satra** [comment]
rendered here: http://nipy.org/workshops/2017-03-boston/lectures/nipype-multicore-hpc/#1

**Comment by satra** [comment]
i'm planning to add considerations for HPC environments, such as full granular parallelization, parallelize each top level node, etc.,.

**Comment by ccraddock** [comment]
That sounds good. We have an example nipype workflow for FSLs randomise where we parallelize across contrasts that are tested. This can also be extended to run different blocks of the permutations in parallel. This could be demo on how to take a pipeline and increase its parallelization. what do you think? It runs in Docker

**Pull request merged**
