### PR TITLE
[DRAFT] Nibabel/Nilearn tutorial

### PR DESCRIPTION
**Pull request by effigies**
Currently assumes the following Docker environment:

```Dockerfile
FROM miykael/nipype_level0
MAINTAINER Chris Markiewicz <markiewicz@stanford.edu>

USER $NB_USER
RUN pip install --upgrade \
    git+https://github.com/nipy/nibabel.git@ca977abeb77f95ed3a40b7b89c310b286b9885b7#egg=nibabel \
    git+https://github.com/nilearn/nilearn.git@87c12efe14c005f1c916f76358639b55a306fb06#egg=nilearn

COPY bids bids
RUN python -c 'from nilearn import datasets; datasets.fetch_haxby()'
```

Where `bids` is a stripped-down (one T1, one EPI, a few files from a FreeSurfer subjects dir) OpenFMRI dataset.

### CODE REVIEW

**Comment by effigies** [comment]
Going to add a subset of https://nilearn.github.io/auto_examples/plot_decoding_tutorial.html to the end. And will probably clean up the text before Monday. This was mostly trying to get the content back in a document before I forgot it all.

Feel free to criticize, though.

**Comment by effigies** [comment]
@matthew-brett If you have a few minutes before Monday, I'd appreciate your eyes on the first part of [this](https://github.com/effigies/workshops/blob/gh-pages/2017-03-boston/lectures/nibabel_nilearn_tutorial.ipynb). Just to make sure there's nothing wildly inaccurate, or if there's something you feel is important to add for new users.

Context: I've been asked to give a ~50min crash course in manipulating and visualizing neuroimages in Python using nibabel/nilearn.

**Comment by effigies** [comment]
@jbpoline @chrisfilo @akeshavan I believe you're marked in the Google doc as helping on this, so feel free to criticize. It's not quite done (trying to decide how most quickly to do the ML bit; the nilearn example I'm drawing from is more didactic than I'm aiming for), but I think the overall scope is clear.

I also haven't run through this with an eye to time, but I did try to make it so we can cut off after discussing masking, in case there's no time to finish with ML.

**Comment by matthew-brett** [comment]
Chris:

* might be better not to mention DICOM reading capability, as it's not very well advanced;
* the `data` from `get_data` is always exactly a numpy array.  `img.dataobj` can be (usually is) a proxy object that acts like a data array;
* the viewer doesn't work right on all backends - particularly, it doesn't work correctly for macosx backend and matplotlib 2.0 - see http://matplotlib.1069221.n5.nabble.com/Matplotlib-devel-Confusion-about-draw-artist-td47638.html
* you don't need `header.copy()` for the image creation - nibabel already copies the header on the way in;

Looks good otherwise.

**Comment by effigies** [comment]
Thanks for the comments. I'll update DICOM to say "(limited support)", as I think it's worth mentioning, at the very least as a warning. (So they don't see it in the docs later and assume it's got full capabilities.) And I'll add in a warning about OSX.

**Comment by satra** [comment]
@effigies  - just pushed this base container file (it's building right now on dockerhub): 

https://github.com/nipy/workshops/blob/master/170327-nipype/Dockerfile.base 

let me know if there is something missing for your notebook.

```
docker run -it --rm -p8888:8888 -u jovyan 
    -v /outside_notebook_dir/:/home/jovyan/work nipype/workshops:latest-base jupyter-lab
```

**Comment by effigies** [comment]
@satra The nilearn commit I used (or any since surface visualization went
in) would be great.

**Comment by satra** [comment]
> The nilearn commit I used (or any since surface visualization went in) would be great.

done.

**Comment by effigies** [comment]
@satra Any chance of adding `ipywidgets` to the pip list? I don't use it, but its absence makes a `ShimWarning` show up in my imports.

Related to mwaskom/seaborn#874.

**Pull request closed without merging**
