### PR TITLE
[Ready] Materials Day 2, 3pm-4pm: Interfaces & Workflows

### PR DESCRIPTION
**Pull request by oesteban**
## Writing new workflows and interfaces [OE + help:CG]
- Write new interfaces
  - CommandLine interface
  - Pure python interfaces:
    - Function interface
    - BaseInterface -derived interfaces
  - MATLAB interface
- Write a workflow integrating the new interfaces

### CODE REVIEW

**Comment by satra** [comment]
@oesteban - pushed this base container image.

`https://hub.docker.com/r/nipype/workshops/builds/`

just fixed a graphviz issue. now working on extended container with all imaging packages.

**Comment by satra** [comment]
assume `/home/jovyan/work` as the workdir and it should be writeable as discussed on gitter via:

`docker run -it --rm -p8888:8888 -v /path/to/local_workshop_dir:/home/jovyan/work nipype/workshops:latest-base jupyter-lab`

it will also have `data/ds000114` downloaded via datalad

**Comment by oesteban** [comment]
@satra, that Docker image does not have matlab, does it?

**Comment by satra** [comment]
@oesteban - that is correct, i was going to put octave + mcr in the second one. i'll check their size and unless it's a lot, i could put it into the first one.

**Comment by oesteban** [comment]
@satra let me fix the paths to what we are using in the sessions

**Comment by oesteban** [comment]
@satra we're good to go here

**Pull request merged**
